style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/mirakl/terraform-module-template
options:
  commits:
    sort_by: Type
    filters:
      Type:
        # new feature
        - Feature
        # bug fix
        - Fix
        # enhancement
        - Enhancement
        # performance improvement
        - Perf
        # documentation
        - Docs
        # code refactoring
        - Refactor
        # tests
        - Test
        # continous integration
        - CI

  commit_groups:
    group_by: Type
    sort_by: Type
    title_maps:
      Feature: Features
      Fix: Bug Fixes
      Enhancement: Enhancements
      Perf: Performance Improvements
      Docs: Documentation
      Refactor: Code Refactoring
      Test: Tests
      CI: Continous Integration

  header:
    pattern: "^(.+)\\s*:\\s*(.+)$"
    pattern_maps:
      - Type
      - Subject

  notes:
    keywords:
      - BREAKING CHANGES
      - NOTES

  refs:
    actions:
      - Closes
      - Fixes
      - Resolves
